on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formats:
    name: Check format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: CheckFormat
        run: |
         dotnet tool install -g dotnet-format
         dotnet format --verify-no-changes --include PartsTreeSystem/ -v diag
         dotnet format --verify-no-changes --include PartsTreeSystemExample/ -v diag
         dotnet format --verify-no-changes --include PartsTreeSystemTest/ -v diag
        shell: sh

      - name: Test
        run: |
         dotnet build PartsTreeSystemTest/
         dotnet test PartsTreeSystemTest/
        shell: sh
